-keep class com.pushfa.sdk.PushfaFirebaseMessagingService { *; }
-keep class com.pushfa.sdk.internal.PushfaNotificationClickActivity { *; }
-keep class com.pushfa.sdk.internal.PushfaReportWorker { *; }
